#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-indirect
Version  : 0.38
Release  : 8
URL      : https://cpan.metacpan.org/authors/id/V/VP/VPIT/indirect-0.38.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/V/VP/VPIT/indirect-0.38.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libi/libindirect-perl/libindirect-perl_0.38-1.debian.tar.xz
Summary  : 'Lexically warn about using the indirect method call syntax.'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-indirect-lib = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
NAME
indirect - Lexically warn about using the indirect method call syntax.
VERSION
Version 0.38

%package dev
Summary: dev components for the perl-indirect package.
Group: Development
Requires: perl-indirect-lib = %{version}-%{release}
Provides: perl-indirect-devel = %{version}-%{release}

%description dev
dev components for the perl-indirect package.


%package lib
Summary: lib components for the perl-indirect package.
Group: Libraries

%description lib
lib components for the perl-indirect package.


%prep
%setup -q -n indirect-0.38
cd ..
%setup -q -T -D -n indirect-0.38 -b 1
mkdir -p deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/indirect-0.38/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.1/x86_64-linux-thread-multi/indirect.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/indirect.3

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.1/x86_64-linux-thread-multi/auto/indirect/indirect.so
