#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-indirect
Version  : 0.39
Release  : 11
URL      : https://cpan.metacpan.org/authors/id/V/VP/VPIT/indirect-0.39.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/V/VP/VPIT/indirect-0.39.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libi/libindirect-perl/libindirect-perl_0.38-1.debian.tar.xz
Summary  : Perl/CPAN Module indirect: Lexically warn about using the indirect method call syntax.
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-indirect-lib = %{version}-%{release}
Requires: perl-indirect-license = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
NAME
indirect - Lexically warn about using the indirect method call syntax.
VERSION
Version 0.39

%package dev
Summary: dev components for the perl-indirect package.
Group: Development
Requires: perl-indirect-lib = %{version}-%{release}
Provides: perl-indirect-devel = %{version}-%{release}
Requires: perl-indirect = %{version}-%{release}
Requires: perl-indirect = %{version}-%{release}

%description dev
dev components for the perl-indirect package.


%package lib
Summary: lib components for the perl-indirect package.
Group: Libraries
Requires: perl-indirect-license = %{version}-%{release}

%description lib
lib components for the perl-indirect package.


%package license
Summary: license components for the perl-indirect package.
Group: Default

%description license
license components for the perl-indirect package.


%prep
%setup -q -n indirect-0.39
cd ..
%setup -q -T -D -n indirect-0.39 -b 1
mkdir -p deblicense/
cp -r %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/indirect-0.39/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-indirect
cp deblicense/copyright %{buildroot}/usr/share/package-licenses/perl-indirect/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.2/x86_64-linux-thread-multi/indirect.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/indirect.3

%files lib
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.2/x86_64-linux-thread-multi/auto/indirect/indirect.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-indirect/deblicense_copyright
